dist: xenial

addons:
 apt:
  packages:
  - binutils-mingw-w64-i686
  - binutils-mingw-w64-x86-64
  - gcc-mingw-w64-i686
  - gcc-mingw-w64-x86-64
  - gcc
  - make

language: c

script: make clean && make

notifications:
 webhooks:
  urls:
  - https://webhooks.gitter.im/e/0193b78e3a39374966e6
  on_success: change  # options: [always|never|change] default: always
  on_failure: always  # options: [always|never|change] default: always
  on_start: never     # options: [always|never|change] default: always

